version: '2.29'

services:
  app:
    build:
      context: ../
      dockerfile: docker/dockerfile
      args:
        APP_VERSION: 1.0
    image: my-spring-app:1.0
    container_name: my-spring-app-container
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/hello || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s