FROM openjdk:17
LABEL maintainer = "Hugo"
RUN mkdir target
COPY ./target/learnSpring5-0.0.1-SNAPSHOT.jar target/app.jar
WORKDIR /target
RUN bash -c "touch app.jar"
ENTRYPOINT ["java", "-jar", "app.jar"]